language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rework' ]; then cd .. && eval "mv $currentfolder generator-rework" && cd generator-rework; fi
